### ISSUE TITLE
More rules

### ISSUE THREAD

**Issue by chockenberry** [kerri-hicks/hide_twitter_right_column_2019#1]
Because the columns are in a flexbox, the `primaryColumn` aligns weirdly when the `sidebarColumn` is hidden. I got around it with this rule:

```css
div[data-testid="primaryColumn"] {
	margin-left: 0px !important;
}
```

Also, I find this rule to change the header's fixed position to relative to be an improvement:

```css
header > div > div {
	position: relative !important;
}
```
